name: Build/test/run

on: [ push ]

jobs:
  build-test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --release
      - name: Run
        run: "ls -d day_* | xargs -I '{}' cargo run --release --bin '{}'"
