name: Test + run

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --tests
      - name: Test
        run: cargo test --release
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Run
        run: "ls -d day_* | xargs -I '{}' cargo run --release --quiet --bin '{}'"
